import json


class Config:
    def __init__(self):
        with open("Config/config.json") as config_file:
            self.config = json.load(config_file)
        self.mainWindowSize = self.config["mainWindowSize"]
        self.mainMenuTexture = self.config["mainMenuTexture"]
        self.mainMenuSelector = self.config["mainMenuSelector"]
        self.gameOverTexture = self.config["gameOverTexture"]
        self.currentStageTexture = self.config["currentStageTexture"]
        self.endOfStageOnePlayerTexture = self.config["endOfStageOnePlayerTexture"]
        self.endOfStageTwoPlayersTexture = self.config["endOfStageTwoPlayersTexture"]
        self.endOfStageCurrentStageContainer = self.config["endOfStageCurrentStageContainer"]
        self.endStageTanksPerPlayerCounterContainer = self.config["endStageTanksPerPlayerCounterContainer"]
        self.endOfStageSeparateTankPointsContainer = self.config["endOfStageSeparateTankPointsContainer"]
        self.endOfStageTotalPlayerPointsContainer = self.config["endOfStageTotalPlayerPointsContainer"]
        self.endOfStageTotalTanksContainer = self.config["endOfStageTotalTanksContainer"]
        self.hiscoreAnimation = self.config["hiscoreAnimation"]
        self.hiscoreNumbers = self.config["hiscoreNumbers"]
        self.winnerScreenPlayer1Animation = self.config["winnerScreenPlayer1Animation"]
        self.winnerScreenPlayer2Animation = self.config["winnerScreenPlayer2Animation"]
        self.winnerScreenTieAnimation = self.config["winnerScreenTieAnimation"]
        self.numberColors = self.config["numberColors"]
        self.numberSize = self.config["numberSize"]
        self.numbers = self.config["numbers"]
        self.playersLives = self.config["playersLives"]
        self.initialPlayerLives = self.config["initialPlayerLives"]
        self.baseTextures = self.config["baseTextures"]
        self.blockTextures = self.config["blockTextures"]
        self.hudEnemy = self.config["hudEnemy"]
        self.hudEnemyContainer = self.config["hudEnemyContainer"]
        self.hudEnemyContainerWidth = self.config["hudEnemyContainerWidth"]
        self.hudEnemyContainerHeight = self.config["hudEnemyContainerHeight"]
        self.enemySpawnRegionWidth = self.config["enemySpawnRegionWidth"]
        self.enemySpawnRegionHeight = self.config["enemySpawnRegionHeight"]
        self.enemyShootInterval = self.config["enemyShootInterval"]
        self.enemyMovementSpeedMap = self.config["enemyMovementSpeedMap"]
        self.bulletSpeedMap = self.config["bulletSpeedMap"]
        self.enemyTypeIds = self.config["enemyTypeIds"]
        self.enemyTypes = self.config["enemyTypes"]
        self.playerMovementSpeed = self.config["playerMovementSpeed"]
        self.playerLevels = self.config["playerLevels"]
        self.maps = self.config["maps"]
        self.sounds = self.config["sounds"]
